# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-20 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.BooleanField()),
                ('cover', models.BooleanField()),
                ('setting', models.CharField(max_length=40)),
                ('number_of_characters', models.IntegerField()),
                ('number_of_pages', models.IntegerField()),
                ('Deadline', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CommitionLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hire.Commition')),
            ],
        ),
    ]
