# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-20 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0002_auto_20190920_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='commition_prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cover', models.DecimalField(decimal_places=2, max_digits=6)),
                ('number_of_characters', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
