# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-20 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0003_commition_prices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='commition_prices',
        ),
        migrations.RemoveField(
            model_name='commitionlineitem',
            name='commition',
        ),
        migrations.DeleteModel(
            name='CommitionLineItem',
        ),
    ]
