# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-25 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0004_auto_20190920_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='commition',
            name='yourname',
            field=models.CharField(default='Name', max_length=40),
        ),
    ]
