# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-27 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0008_auto_20190927_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commition',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='commition',
            name='cover',
        ),
    ]
