# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-30 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0010_auto_20190927_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commition',
            name='setting',
            field=models.CharField(max_length=500),
        ),
    ]
